### ISSUE TITLE
Need C code for the AVR32 Bit MCU (EVK1100)

### ISSUE THREAD

**Issue by e-3-s** [amoghj98/DS3231#1]
Hi there,

I wanted to use my ds3231 with my evk1100 kit. 
Could you help me out?

It would be awesome if you were convert it t a C library for the 32bit mcu

**Comment by amoghj98** [comment]
Hey there,
Are you using the AVR32 Studio to program your evk1100 kit?

**Comment by e-3-s** [comment]
Hi @amoghj98 ,

nice that you are replying this fast :D
I am using atmel studio 7, with asf

**Comment by e-3-s** [comment]
I have found a lot of arduino librarys but I really don't understand how to use them.
My teacher said that it is possible the only thing is that I am writing my code in C and most of the librarys are in Cpp.

And are written for the arduinos and not the 32bit avrs. 
Also the EVK1100 uses TWI interface

**Comment by amoghj98** [comment]
TWI is the same as I2C

**Comment by amoghj98** [comment]
And converting cpp to c shouldn't be much of a problem

**Comment by amoghj98** [comment]
Have you tried forking the arduino library for I2C (Wire.h) and converting it to c?

**Comment by amoghj98** [comment]
You can find the source code for the Wire.h library here:
https://github.com/esp8266/Arduino/blob/master/libraries/Wire

**Comment by e-3-s** [comment]
Aright aright. Could you help me out with some directions?

This is a TWI master example code that I am using right now, its without the DS3231.
No I didn't trie to fork the arduino library for I2C.
I am a student sorry haha.

Trying to learn this stuff.

The example code. >>

`/*****************************************************************************
 *
 * \file
 *
 * \brief TWI master example driver for AVR32 UC3.
 *
 * This file provides an example for the TWI on AVR32 UC3 devices.
 *
 * Copyright (c) 2009-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 ******************************************************************************/

/*! \mainpage
 * \section intro Introduction
 * This is the documentation for the data structures, functions, variables,
 * defines, enums, and typedefs for the TWI driver single-master mode example.
 *
 * The given example uses one evaluation kit for TWI master (EVK1100, EVK1101 or
 * STK1000) and another one for TWI slave (EVK1100 or EVK1101 to program with
 * SLAVE_EXAMPLE).\n
 * The TWI master performs a few basic checks and prints the results (PASS/FAIL)
 * on USART1. The checks are:
 *    - the TWI master probes the TWI slave,
 *    - the TWI master performs a write access to the TWI slave,
 *    - the TWI master performs a read access of what it just wrote to the TWI slave,
 *    - the read data are compared with the originally written data.
 *
 * \section validationprocedure Validation Procedure
 * - Connect a UART monitor on the UART_1 of the board with TWI master
 * - Connect the TWI master with TWI slave (VCC=VCC,SDA=SDA,SCL=SCL,GND=GND)
 * - Compile a master and a slave firmware with same configuration (addr mode,speed)
 * - Program the master and slave boards
 * - RESET Slave board (=reset TWI memory)
 * - Release RESET on MASTER board
 * - on UART, you see all tests PASS
 * - Release RESET on MASTER board
 * - on UART, you see always all tests PASS.
 *
 * \section files Main Files
 * - twi.c: TWI driver;
 * - twi.h: TWI driver header file;
 * - twi_master_example.c: TWI single-master mode example application.
 *
 * \section compinfo Compilation Info
 * This software is written for GNU GCC for AVR32 and for IAR Embedded Workbench
 * for Atmel AVR32. Other compilers may or may not work.
 *
 * You can change the following defines but you should make sure that there are
 * the same on the TWI slave side for the tests to pass:
 * - TWI slave (memory) address (\ref EEPROM_ADDRESS)
 * - Address of the virtual mem in the EEPROM (\ref VIRTUALMEM_ADDR_START)
 * - Address length of the EEPROM memory (\ref EEPROM_ADDR_LGT)
 * - speed in Hz (\ref TWI_SPEED).
 *
 * \section deviceinfo Device Info
 * All AVR32 devices with a TWI module can be used.
 *
 * \section configinfo Configuration Information
 * This example has been tested with the following configuration:
 * - EVK1100 or EVK1101 evaluation kit, or STK1000 starter kit;
 * - CPU clock: 12 MHz;
 * - USART1 connected to a PC serial port via a standard RS232 DB9 cable;
 * - PC terminal settings:
 *   - 57600 bps,
 *   - 8 data bits,
 *   - no parity bit,
 *   - 1 stop bit,
 *   - no flow control.
 *
 * \section contactinfo Contact Information
 * For further information, visit
 * <A href="http://www.atmel.com/products/AVR32/">Atmel AVR32</A>.\n
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */


#include <avr32/io.h>
#include "board.h"
#include "print_funcs.h"
#include "gpio.h"
#include "pm.h"
#include "twi.h"


//------------------  C O N F I G U R A T I O N S  -------------------

#define EEPROM_ADDRESS        0x50        // EEPROM's TWI address
#define EEPROM_ADDR_LGT       3           // Address length of the EEPROM memory
#define VIRTUALMEM_ADDR_START 0x123456    // Address of the virtual mem in the EEPROM
#define TWI_SPEED             50000       // Speed of TWI

//------------------  D E F I N I T I O N S  -------------------

//! \brief Constants to define the sent and received pattern
#define  PATTERN_TEST_LENGTH        (sizeof(test_pattern)/sizeof(U8))
const U8 test_pattern[] =  {
   0xAA,
   0x55,
   0xA5,
   0x5A,
   0x77,
   0x99};


//--------------------------------------------------------------------------------------------------------------
//----------------------------------------- T W I   M A S T E R ------------------------------------------------
//--------------------------------------------------------------------------------------------------------------

/*! \brief Main function.
 */
int main(void)
{
  static const gpio_map_t TWI_GPIO_MAP =
  {
#if BOARD == EVK1100
    {AVR32_TWI_SDA_0_0_PIN, AVR32_TWI_SDA_0_0_FUNCTION},
    {AVR32_TWI_SCL_0_0_PIN, AVR32_TWI_SCL_0_0_FUNCTION}
#elif BOARD == EVK1101
    {AVR32_TWI_SDA_0_0_PIN, AVR32_TWI_SDA_0_0_FUNCTION},
    {AVR32_TWI_SCL_0_0_PIN, AVR32_TWI_SCL_0_0_FUNCTION}
#elif BOARD == EVK1104
#error This example only supports AVR UC3 with a TWI module. UC3 A3 series have a TWIM module.
#elif BOARD == EVK1105
    {AVR32_TWI_SDA_0_0_PIN, AVR32_TWI_SDA_0_0_FUNCTION},
    {AVR32_TWI_SCL_0_0_PIN, AVR32_TWI_SCL_0_0_FUNCTION}
#elif BOARD == STK1000
    {AVR32_TWI_SDA_0_PIN, AVR32_TWI_SDA_0_FUNCTION},
    {AVR32_TWI_SCL_0_PIN, AVR32_TWI_SCL_0_FUNCTION}
#else
#  error The TWI configuration to use in this example is missing.
#endif
  };
  twi_options_t opt;
  twi_package_t packet, packet_received;
  int status, i;

  U8 data_received[PATTERN_TEST_LENGTH] = {0};

#if BOARD == EVK1100 || BOARD == EVK1101

  // Switch to oscillator 0
  pm_switch_to_osc0(&AVR32_PM, FOSC0, OSC0_STARTUP);

#endif

  // Init debug serial line
  init_dbg_rs232(FOSC0);

  // Initialize and enable interrupt
  irq_initialize_vectors();
  cpu_irq_enable();

  // Display a header to user
  print_dbg("\x0C\r\nTWI Example\r\nMaster!\r\n");

  // TWI gpio pins configuration
  gpio_enable_module(TWI_GPIO_MAP, sizeof(TWI_GPIO_MAP) / sizeof(TWI_GPIO_MAP[0]));

  // options settings
  opt.pba_hz = FOSC0;
  opt.speed = TWI_SPEED;
  opt.chip = EEPROM_ADDRESS;

  // initialize TWI driver with options
  status = twi_master_init(&AVR32_TWI, &opt);
  // check init result
  if (status == TWI_SUCCESS)
  {
    // display test result to user
    print_dbg("Probe test:\tPASS\r\n");
  }
  else
  {
    // display test result to user
    print_dbg("Probe test:\tFAIL\r\n");
  }

  // TWI chip address to communicate with
  packet.chip = EEPROM_ADDRESS;
  // TWI address/commands to issue to the other chip (node)
  packet.addr[0] = VIRTUALMEM_ADDR_START >> 16;
  packet.addr[1] = VIRTUALMEM_ADDR_START >> 8;
  packet.addr[2] = VIRTUALMEM_ADDR_START;
  // Length of the TWI data address segment (1-3 bytes)
  packet.addr_length = EEPROM_ADDR_LGT;
  // Where to find the data to be written
  packet.buffer = (void*) test_pattern;
  // How many bytes do we want to write
  packet.length = PATTERN_TEST_LENGTH;

  // perform a write access
  status = twi_master_write(&AVR32_TWI, &packet);

  // check write result
  if (status == TWI_SUCCESS)
  {
    // display test result to user
    print_dbg("Write test:\tPASS\r\n");
  }
  else
  {
    // display test result to user
    print_dbg("Write test:\tFAIL\r\n");
  }

  // TWI chip address to communicate with
  packet_received.chip = EEPROM_ADDRESS ;
  // Length of the TWI data address segment (1-3 bytes)
  packet_received.addr_length = EEPROM_ADDR_LGT;
  // How many bytes do we want to write
  packet_received.length = PATTERN_TEST_LENGTH;
  // TWI address/commands to issue to the other chip (node)
  packet_received.addr[0] = VIRTUALMEM_ADDR_START >> 16;
  packet_received.addr[1] = VIRTUALMEM_ADDR_START >> 8;
  packet_received.addr[2] = VIRTUALMEM_ADDR_START;
  // Where to find the data to be written
  packet_received.buffer = data_received;

  // perform a read access
  status = twi_master_read(&AVR32_TWI, &packet_received);

  // check read result
  if (status == TWI_SUCCESS)
  {
    // display test result to user
    print_dbg("Read Test:\tPASS\r\n");
  }
  else
  {
    // display test result to user
    print_dbg("Read test:\tFAIL\r\n");
  }

  // check received data against sent data
  for (i = 0 ; i < PATTERN_TEST_LENGTH; i++)
  {
    if (data_received[i] != test_pattern[i])
    {
      // a char isn't consistent
      print_dbg("Check Read:\tFAIL\r\n");
      // Error
      while(1);
    }
  }

  // everything was OK
  print_dbg("Check Read:\tPASS\r\n");

  while(1);
}
`

**Comment by e-3-s** [comment]
I don't understand what to do with a arduino twi.h library?

I already have a twi.h included.
Sorry mister could you be more specific, I am really noob at this. 
Arduino is not a problem but this ...hmmm

**Comment by amoghj98** [comment]
The Arduino library is easier to understand. Manufacturer-supplied libraries (such as the one you've mentioned above) are generally written in a way that is difficult to understand. Also, they tend to occupy more code space. You could try using a c version of the Arduino library.

**Comment by amoghj98** [comment]
Or send me the errors you are receiving on compiling your code. I can't say anything by looking at the library.

**Comment by e-3-s** [comment]
Aright. I have included the two files. the rtc.h and rtc.cpp in my projects folder.
Also in my main program file I have included the rtc.h

Getting the following errors >>

Severity	Code	Description	Project	File	Line
Error		Arduino.h: No such file or directory	TWI_MASTER_EXAMPLE1	C:\Users\Edris-Lappie\Documents\Atmel Studio\7.0\TWI_MASTER_EXAMPLE1\TWI_MASTER_EXAMPLE1\src\rtc.h	9


Next error >>


Severity	Code	Description	Project	File	Line
Error		expected '=', ',', ';', 'asm' or '__attribute__' before 'rtc'	TWI_MASTER_EXAMPLE1	C:\Users\Edris-Lappie\Documents\Atmel Studio\7.0\TWI_MASTER_EXAMPLE1\TWI_MASTER_EXAMPLE1\src\rtc.h	26
 

Next error >>

Severity	Code	Description	Project	File	Line
Error		recipe for target 'src/twi_master_example.o' failed	TWI_MASTER_EXAMPLE1	C:\Users\Edris-Lappie\Documents\Atmel Studio\7.0\TWI_MASTER_EXAMPLE1\TWI_MASTER_EXAMPLE1\Debug\Makefile	239

**Comment by amoghj98** [comment]
If you wish to use the library supplied by Microchip, (which is indeed, advisable) I would recommend that you first study the I2C protocol and then approach the problem at hand. It will make it easier for you to both understand the errors in your code, and to express your doubts properly. That way, your fellow github users will be able to assist you better.

**Comment by amoghj98** [comment]
Try deleting the line
#include <Arduino.h> 
from my code and compile again

**Comment by e-3-s** [comment]
Aright I deleted the arduino.h line.
That error is gone.

Still got 2 errors remaining...

Severity	Code	Description	Project	File	Line
Error		expected '=', ',', ';', 'asm' or '__attribute__' before 'rtc'	TWI_MASTER_EXAMPLE1	C:\Users\Edris-Lappie\Documents\Atmel Studio\7.0\TWI_MASTER_EXAMPLE1\TWI_MASTER_EXAMPLE1\src\rtc.h	26


and


Severity	Code	Description	Project	File	Line
Error		recipe for target 'src/twi_master_example.o' failed	TWI_MASTER_EXAMPLE1	C:\Users\Edris-Lappie\Documents\Atmel Studio\7.0\TWI_MASTER_EXAMPLE1\TWI_MASTER_EXAMPLE1\Debug\Makefile	239

**Comment by amoghj98** [comment]
and add the line
#include <stdint.h>
in its place

**Comment by e-3-s** [comment]
Aright added #include <stdint.h> in its place.
No errors only the 2 mentioned above

**Comment by amoghj98** [comment]
could you send me a picture of the piece of code where these errors occur?

**Comment by e-3-s** [comment]
Sure.

https://ibb.co/ibBcGL is the recipe error

https://ibb.co/fTKKVf is the expected error

**Comment by amoghj98** [comment]
You are probably missing a semicolon somewhere

**Comment by amoghj98** [comment]
Just a moment

**Comment by amoghj98** [comment]
What compiler are you using in Studio 7?

**Comment by e-3-s** [comment]
Uhm I don't know? The main compiler I think?

**Comment by amoghj98** [comment]
Try removing the file twi_master....... from your project and compile again

**Comment by amoghj98** [comment]
> Uhm I don't know? The main compiler I think?

I mean does it use gcc or some other gnu compiler

**Comment by e-3-s** [comment]
Oke.... Do you mean the arduino.h file?
Or do you mean the rtc.h arduino library?

And also what do you mean by fork?

**Comment by amoghj98** [comment]
Try loading the Arduino library instead of twi.h.... but make the necessary changes such as the appropriate pin numbers,etc.

**Comment by amoghj98** [comment]
Are you new to github?

**Comment by amoghj98** [comment]
> Oke.... Do you mean the arduino.h file?
> Or do you mean the rtc.h arduino library?
> 
> And also what do you mean by fork?

I mean the library Wire.h

**Comment by e-3-s** [comment]
Yes !!! new to github

**Comment by amoghj98** [comment]
> Yes !!! new to github

Ok, go to this link:
https://github.com/esp8266/Arduino/blob/master/libraries/Wire
There, you'll find a button that says 'fork' in the top right corner

**Comment by e-3-s** [comment]
So you mean. change wire.h to a avr32 bit options
Then include that new wire.h in my project.

And that way your library can work?

**Comment by amoghj98** [comment]
Pressing that button will copy the 'Wire.h' library to your own github page. Then, download the files and include them in your project

**Comment by amoghj98** [comment]
> Try loading the Arduino library instead of twi.h.... but make the necessary changes such as the appropriate pin numbers,etc.

But don't forget this

**Comment by amoghj98** [comment]
> So you mean. change wire.h to a avr32 bit options
> Then include that new wire.h in my project.
> 
> And that way your library can work?

What does that mean?

**Comment by e-3-s** [comment]
Arightt... I am gonna try bro :D:D

So I have to change wire.h pin numbers etc to the pin numbers of my board?

**Comment by amoghj98** [comment]
After making the appropriate changes, compile the code and it should work

**Comment by e-3-s** [comment]
Arightt I really don't know what I have to change. 
Cause looking at the code form wire.h and wire.cpp 
I am loosing my mind bro xD
I don't know where to start but I will try

**Comment by amoghj98** [comment]
If it doesn't work, wait. I might be able to give you a c library by tomorrow, but don't get your hopes up. I'll have to brush up on my AVR, first ;)

**Comment by amoghj98** [comment]
> Arightt I really don't know what I have to change.
> Cause looking at the code form wire.h and wire.cpp
> I am loosing my mind bro xD
> I don't know where to start but I will try

What fun is code without a few brain-freezes? xD

**Comment by e-3-s** [comment]
Whaattttttttttttt :D:D:D

That would be awesome.. Yeah that's true. But this AVR 32 Bit MCU is new to me and 
also the IDE is new to me.

So I am feeling a nooby xD
I have to go. But I will try it in the evening today :D:D:D
Thanks a lot for your effort en replys.

Would be awesome if you include a C library for AVR32 Bit MCU's in your github page

Peace

**Comment by amoghj98** [comment]
Oh, no worries and peace to you too.....

**Comment by amoghj98** [comment]
Hey there, e-3-s,
Here's a library that you might find handy:
https://github.com/akafugu/ds_rtc_lib/tree/master/library-gcc
And don't forget to reply if you find it useful

**Comment by e-3-s** [comment]
Hi @amoghj98 I am back.

Uhm Yeah I tried that. But the problem is that I am confused on how to use that.
Cause when I start that TWI master example project It has already a twi.h

Also I don't know which one to use. Is it the twi.h or the twi-lowlevel.h or both?

**Comment by e-3-s** [comment]
It has also a test folder with more stuff in it.
I am confused do I have to use that or not?

That library has no guide or something

**Comment by e-3-s** [comment]
I know that this is very specialised stuff, but I am in the beginning of learning this so that's why I need some help with it.

And asking the teacher everytime is also not recommended :P

**Comment by amoghj98** [comment]
For example, create an object of the structure 'tm' with constituent variables hour,minute,seconds and pass them to the functions as required.

**Comment by amoghj98** [comment]
@e-3-s have you tried the other library? I've tried that library on Studio 7 and it works for me

**Comment by e-3-s** [comment]
Hi @amoghj98 
Well I have a question. I am working now on in. I want to make a new project. 
My teacher told me something about ASF and C/C++ the only thing is does it matter?
Which one did you choose?

**Comment by e-3-s** [comment]
A lot of error. Didn't change anything. Made a new gcc executable project. 
Imported the files that you said.

Rebuild the solution.

And then these error came
https://ibb.co/jDHzy0

**Comment by e-3-s** [comment]
https://ibb.co/dsbbd0

**Comment by e-3-s** [comment]
Most of the errors are in the twi-lowlevel.c

**Comment by e-3-s** [comment]
Deleted the low-level.c and low-level.h files
2 Errors remaining

https://ibb.co/cN6jy0

**Comment by e-3-s** [comment]
Changed the avr to avr32 in the rtc files.
No errors remaining. 

Only 1 warning.


And now I can use it? Or should I still make those structs?

**Comment by e-3-s** [comment]
Too good to be true. It does need the twi-lowlevel.h and twi-lowlevel.c

**Comment by amoghj98** [comment]
It will indeed need the twi-lowlevel files. Most of the functions in twi.h use the functions defined in twi-lowlevel.h

**Comment by amoghj98** [comment]
> Hi @amoghj98
> Well I have a question. I am working now on in. I want to make a new project.
> My teacher told me something about ASF and C/C++ the only thing is does it matter?
> Which one did you choose?

I used cpp

**Comment by amoghj98** [comment]
So, did it work?

**Comment by e-3-s** [comment]
Nope

**Comment by e-3-s** [comment]
When you initalize the rtc. error are coming

**Comment by amoghj98** [comment]
In that case, have a chat with the developer of the twi library.
